import Header from "@/components/common/Header";
import Sidebar from "@/components/common/Sidebar";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Tools 121 : Vendor",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased text-slate-500 bg-white`}
        suppressHydrationWarning={true}
        data-theme="main"
      >
        <Header />
        <main className="flex">
          <Sidebar />
          <div className="mt-10 ml-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
